name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential g++

    # Step 3: Build the Virtual Machine
    - name: Compile the C++ code
      run: g++ -o virtual_machine src/main.cpp

    # Step 4: Run the program
    - name: Run Virtual Machine
      run: ./virtual_machine
